"""
Django settings for SU_Kart project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['https://localhost:8000',
                '*',]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Kart.apps.KartConfig',
    'import_export',
    #'users.apps.UsersConfig',
    'payments.apps.PaymentsConfig',
    'crispy_forms',
    'storages'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SU_Kart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, '/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SU_Kart.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend',]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_DIR, '/static') #Used in Production
STATICFILES_DIRS = [os.path.join(PROJECT_DIR, '/assets'),
                    os.path.join(PROJECT_DIR, '/assets/js'),
                    os.path.join(PROJECT_DIR, '/assets/css'),
                    os.path.join(PROJECT_DIR, '/assets/images'),
                    os.path.join(BASE_DIR, 'staticfiles'),
                    os.path.join(BASE_DIR, 'static'),
                    'var/www/static/',
                    ]


# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'


CRISPY_TEMPLATE_PACK = 'bootstrap4'

# STATICFILES_FINDERS =(
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#     'django.contrib.staticfiles.finders.DefaultStorageFinder',
# )

#to send EMAILS
SENDGRID_API_KEY=''
EMAIL_HOST = 'api.sendgrid.com'
EMAIL_HOST_USER ='apikey'
EMAIL_HOST_PASSWORD = SENDGRID_API_KEY
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = ''
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(PROJECT_DIR, 'Kart/media')

LOGIN_REDIRECT_URL ='/product_list'
LOGOUT_REDIRECT_URL ='signin'

# SESSION_COOKIE_SAMESITE = "Lax"
# CSRF_COOKIE_SAMESITE = "Lax"
# CSRF_COOKIE_DOMAIN = ".paytm.in"
# CSRF_TRUSTED_ORIGINS = ".paytm.in"
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False



#PAYTM_MERCHANT_KEY = os.environ.get('PAYTM_MERCHANT_KEY')
#PAYTM_MERCHANT_ID = os.environ.get('PAYTM_MERCHANT_ID')
#HOST_URL = os.environ.get('HOST_URL')
#PAYTM_WEBSITE = os.environ.get('PAYTM_WEBSITE')
#PAYTM_CALLBACK_URL = "/payments/response/"
#PAYTM_URL = os.environ.get('PAYTM_URL')

PAYTM_MERCHANT_KEY = ""
PAYTM_MERCHANT_ID = ""
HOST_URL = "http://localhost:8080"
PAYTM_CALLBACK_URL = "/payments/response/"
PAYTM_URL = "https://securegw-stage.paytm.in/order/process"

if DEBUG:

    PAYTM_WEBSITE = 'WEBSTAGING'
    HOST_URL = 'http://localhost:8000'
    '''
    In sandbox enviornment you can use following wallet credentials to login and make payment.
    Mobile Number : 7777777777
    Password : Paytm12345
    This test wallet is topped-up to a balance of 7000 Rs. every 5 minutes.

# if DEBUG:
#     PAYTM_MERCHANT_KEY = os.environ.get('PAYTM_MERCHANT_KEY_TEST')
#     PAYTM_MERCHANT_ID = os.environ.get('PAYTM_MERCHANT_ID_TEST')
#     HOST_URL = os.environ.get('HOST_URL')
#     PAYTM_WEBSITE = 'WEBSTAGING'
#     '''
#     In sandbox enviornment you can use following wallet credentials to login and make payment.
#     Mobile Number : 7777777777
#     Password : Paytm12345
#     OTP: 489871
#     This test wallet is topped-up to a balance of 7000 Rs. every 5 minutes.
#     '''
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
#SECURE_SSL_REDIRECT = True


CORS_REPLACE_HTTPS_REFERER      = False
#HOST_SCHEME                     = "http://"
SECURE_PROXY_SSL_HEADER         = None
SECURE_SSL_REDIRECT             = False
SESSION_COOKIE_SECURE           = False
CSRF_COOKIE_SECURE              = False
SECURE_HSTS_SECONDS             = None
SECURE_HSTS_INCLUDE_SUBDOMAINS  = False
SECURE_FRAME_DENY               = False
